export const ROLES = {
  STUDENT: 'STUDENT',
  INSTRUCTOR: 'INSTRUCTOR',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
};

export const PRODUCT_TYPES = {
  TOPIC: 'TOPIC',
  COURSE: 'COURSE',
  WEBINAR: 'WEBINAR',
  LEARNING_PATH: 'LEARNING_PATH',
  CONTENT_OFFERING: 'CONTENT_OFFERING',
};

export const VIDEO_PROCESSING_STATUS = {
  UPLOADING: 'UPLOADING',
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  FAILED: 'FAILED',
};

export const ENTITLEMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  REVOKED: 'REVOKED',
  EXPIRED: 'EXPIRED',
};

export const ORDER_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

export const TRANSACTION_TYPES = {
  ORDER_PAYMENT: 'ORDER_PAYMENT',
  PLATFORM_FEE: 'PLATFORM_FEE',
  INSTRUCTOR_EARNING: 'INSTRUCTOR_EARNING',
  TAX: 'TAX',
  REFUND: 'REFUND',
  CHARGEBACK: 'CHARGEBACK',
  PAYOUT: 'PAYOUT',
  ADJUSTMENT: 'ADJUSTMENT',
  COURSE_CREDIT: 'COURSE_CREDIT',
};

export const PIPELINE_STAGES = {
  VISITOR: 'VISITOR',
  LEAD: 'LEAD',
  REGISTERED: 'REGISTERED',
  TOPIC_INTEREST: 'TOPIC_INTEREST',
  TOPIC_BUYER: 'TOPIC_BUYER',
  MULTI_TOPIC_BUYER: 'MULTI_TOPIC_BUYER',
  COURSE_UPGRADE: 'COURSE_UPGRADE',
  COMPLETED: 'COMPLETED',
  RETURNING_STUDENT: 'RETURNING_STUDENT',
};

export const COMMUNICATION_CHANNELS = {
  WHATSAPP: 'WHATSAPP',
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  TELEGRAM: 'TELEGRAM',
  IN_APP: 'IN_APP',
  VOICE: 'VOICE',
};

export const CONTENT_ACCESS_TYPES = {
  FREE: 'FREE',
  PAID: 'PAID',
  PURCHASED: 'PURCHASED',
  ENROLLED: 'ENROLLED',
  SUBSCRIPTION: 'SUBSCRIPTION',
  ROLE_BASED: 'ROLE_BASED',
};
